@startuml
skinparam handwritten true

skinparam usecase {
	BackgroundColor DarkSalmon
	BorderColor Black

	BackgroundColor<< Context >> DarkRed
	BorderColor<< Context >> DarkRed

	ActorBackgroundColor<< Human >> Green
  ActorBackgroundColor<< Object >> Silver
}

skinparam component {
	BackgroundColor DarkSeaGreen
	BorderColor Black
}

actor Alice << Human >>
actor Customer <<Human>>
actor Office <<Object>> as "Office Room"

rectangle "Smart Contextual Assistance App" {
  usecase voiceH <<Hyperty Connector>> as "**SmartVoice**
  --
  Hyperty to Handle Audio
  and Video Communications"

	component Connection <<Connection Object>> as comObj

	component "Connection Context" <<Context Object>> as ctxtObj

	voiceH -down-> comObj

	voiceH -down-> ctxtObj

  usecase contactsH <<Hyperty Context>> as "**SmartContacts**
  --
  Hyperty to Handle
  a presence enriched
  Contact List"

	component UserProfile <<Identity Object>> as idObj

	component "Presence" <<Context Object>> as presObj

	contactsH -down-> idObj

	contactsH -down-> presObj

	contactsH -[hidden]up- comObj

	usecase myBraH <<Hyperty Context>> as "**MyBracelet**
  --
  Hyperty to Collect
	and publish data
	from a Bracelet"

	component "Bracelet Data" <<Context Object>> as myBraObj

	myBraH -down-> myBraObj

	myBraH -[hidden]up- presObj

	usecase myCtxtH <<Hyperty Context>> as "**MyHealthContext**
  --
  Hyperty to Handle
  an Human individual
	Health context"

	component "Individual Context" <<Context Object>> as myCtxtObj

	myCtxtH -up-> myBraObj

	myCtxtH -down-> myCtxtObj


	usecase myWorkoutBuddyH <<Hyperty>> as "**My Fitness Buddy**
  --
  Hyperty to Handle
  Fitness Buddy matches
	and the setup of
	Fitness Buddy Sessions"

	myWorkoutBuddyH -up-> myCtxtObj

	usecase myCoachH <<Hyperty>> as "**My Coach**
  --
  Hyperty to Handle
  Personal Coach tracking
	and the setup of
	Coaching Sessions"

	myCoachH -up-> myCtxtObj

	usecase roomH <<Hyperty Context>> as "**Room**
  --
  Hyperty to Handle
  a Room context"

	component "Room Context" <<Context Object>> as roomCtxtObj

	roomH -down-> roomCtxtObj

	roomH -[hidden]up- myWorkoutBuddyH

}

actor Buddy <<Human>> as "Workout Buddy"
actor Coach <<Human>> as "Coach"

Alice .left- voiceH
Customer .right- voiceH
Alice .left- contactsH
Alice .left- myCtxtH
Alice .left- myBraH
Alice .left- myWorkoutBuddyH
Buddy .right- myWorkoutBuddyH
Alice .left- myCoachH
Coach .right- myCoachH
Office .left- roomH

@enduml
