@startuml
!include h2h-use-cases.puml

usecase (Smart Contextual Business Assistance) as bizzAssistUC

usecase (Smart Contextual Business Communication) as bizzCommUC
usecase (Smart Contextual co-worker Communication) as bizzCoworkerCommUC
usecase (Smart Contextual Partner Communication) as bizzPartnerCommUC

rectangle "Customer Communication" {
  usecase (Smart Contextual Customer Communication) as bizzClientCommUC

  usecase contextualRouting2AgentUC as "Contextual routing\n
  of Customer Assistance Request\n
  to the most appropriate\n
  collaborator"

  usecase contextualAgentAvailabilityUC as "Contextual Management\n
  of Agent availability"

  contextualRouting2AgentUC -[hidden]up- contextualAgentAvailabilityUC

  usecase showProductUC as "Show Product\nduring Customer Communication"

  contextualRouting2AgentUC -[hidden]down- showProductUC

  usecase salesUC as "Support Product Sales\nduring Customer Communication"

  salesUC -[hidden]up- showProductUC

  usecase evaluationUC as "Custumer Evaluates\nAssistance"

  salesUC -[hidden]down- evaluationUC

  usecase awardAgentUC as "collaborator is awarded\naccording to Customer\nAssistance outcome"

  awardAgentUC -[hidden]up- evaluationUC
}


bizzAssistUC <|-right-- bizzCommUC

chatUC <.. bizzCommUC : <<includes>>
callUC <.. bizzCommUC : <<includes>>
videoUC <.. bizzCommUC : <<includes>>
screenUC <.. bizzCommUC : <<includes>>
fileUC <.. bizzCommUC : <<includes>>
presenceUC <.. bizzCommUC : <<includes>>

bizzCommUC <|-- bizzCoworkerCommUC
bizzCommUC <|-- bizzClientCommUC
bizzCommUC <|-- bizzPartnerCommUC

bizzClientCommUC ..> contextualAgentAvailabilityUC : <<includes>>
bizzClientCommUC ..> contextualRouting2AgentUC : <<includes>>
bizzClientCommUC ..> showProductUC : <<includes>>
bizzClientCommUC ..> salesUC : <<includes>>
bizzClientCommUC ..> evaluationUC : <<includes>>
bizzClientCommUC ..> awardAgentUC : <<includes>>

@enduml
