@startsalt
{+
  <&grid-four-up> joelpinheiro <&account-logout>
  ==
  {
  {[Call] | [<b>Video] | [Chat]} 
  ~~
  {{+*************************************************
   *<Xframe>*
    *************************************************}  |  
    {+*************************************************
*<Yframe>*
    *************************************************}}
  }
  Video call to <&person> pchainho
    10:18
  [Hang up]
  --
}
@endsalt
