@startsalt
{+
  <&grid-four-up> joelpinheiro <&account-logout>
  ==
  {
  {[Audio] | [<b>Video] | [Chat]}
  ~~
  {+********************************************************************************************
  ********************************************************************************************
   *<pchai_frame_x>*
   ********************************************************************************************
    ********************************************************************************************}
  }
  Video call to <&person> pchainho
    10:18
  [Hang up]
  --
}
@endsalt
