@startuml
autonumber

participant "App" as app

participant "WRTC\nAPI" as wrtcAPI

participant "Connector\nHyperty" as voiceH

participant "Connection\nController" as connCtrl

participant "Connection\nData Object" as Conn

participant "Message Factory" as msgF

participant "Syncher" as sync

participant "Message BUS" as bus

app ->  voiceH : addListener( callback )

app ->  voiceH : connect( bobIdentifier, options )

group discover Bob

voiceH -> msgF : createDiscoveryMessage( bobIdentifier, scope )

voiceH <-- msgF : return discoveryBobMessage

voiceH -> bus : postMessage( discoveryBobMessageReq )

...

voiceH <- bus : postMessage( discoveryBobMessageRes )

voiceH -> msgF : getDiscoveryResponse( discoveryBobMessageRes )

voiceH <-- msgF : bobHypertyURL

end group

newpage

group Connection Invite Bob

voiceH -> wrtcAPI : get CommResources\n(incl SDP)

voiceH <-- wrtcAPI : return CommResources\n(incl SDP)

voiceH -> sync : create\n( connectionObjSchema, CommResources, bobHypertyURL )

create Conn

sync -> Conn : new()

sync -> sync : Object.observe( Connection )

sync -> bus : postMessage( createConnectionObjectReqMsg )

...

sync <- bus : postMessage( createConnectionObjectResOkMsg )

voiceH <-- sync : return ConnectionDataObject

end group

create connCtrl

voiceH -> connCtrl : new( ConnectionDataObject )

app <-- voiceH :  return ConnectionController

@enduml
