@startuml "contextual-communication-design.png"

Package ContextualComm {

	class ContextualComm {
	trigger : ContextualCommTrigger[]
	}

	class ContextualCommTrigger {
	contextName ?: string
	contextScheme ?: string
	contextResource ?: HypertyResource.HypertyResourceType
	values : Context.ConntextValue[]
	}

	note bottom : Context Values that triggers ContextualComm.\n Discovered with one of these: Context Object name,\n Context scheme or Hyperty Resource

	class CompositeContextualComm {
	}

	class AtomicContextualComm {
	}

	class CompositeContextualComm {
	}

 ContextualComm -right-> "1..*" ContextualCommTrigger

	CompositeContextualComm *-"0..*" CompositeContextualComm

	ContextualComm -up-|> ActivityContext.ActivityContext

	ContextualComm -up-|> Communication.Communication

	CompositeContextualComm -up-|> ContextualComm

	AtomicContextualComm -up-|> ContextualComm
}

@enduml
