@startuml
!include m2m-use-cases.puml
!include h2m-use-cases.puml

usecase (Smart Contextual Business Assistance) as bizzAssistUC

rectangle "Office Automation" {
  usecase (Smart Contextual Office Automation) as officeAutoUC


}

bizzAssistUC <|-right-- officeAutoUC

lightCtrlUC <.up.. officeAutoUC : <<includes>>
temperatureCtrlUC <.up.. officeAutoUC : <<includes>>
videoMonitorUC <.up.. officeAutoUC : <<includes>>
temperatureUC <.up. officeAutoUC : <<includes>>
lightUC <.up. officeAutoUC : <<includes>>
powerUC <.up. officeAutoUC : <<includes>>


@enduml
