@startuml

== Login ==

AlicesDevice -> CSP: login
AlicesDevice <-- CSP: Hyperties

== Load Graph Data ==



AlicesDevice -> Host: download Graph Data
note right
If Alice is using a mobile device, loading
locally stored graph data could be automatized.
end note
AlicesDevice <-- Host: Graph Data
AlicesDevice <- AlicesDevice: load Graph Data

== Look up Bob and call him ==

AlicesDevice -> GlobalRegistry: look up Bob
AlicesDevice <-- GlobalRegistry: Bob's Domain Registries
AlicesDevice -> BobsDomainRegistry: look up Bob's live Hyperties

alt Restricted Access to Bob's Information
AlicesDevice -> BobsDomainRegistry: Login
end

AlicesDevice <-- BobsDomainRegistry: Bob's live Hyperties (incl. related Messaging Nodes)
AlicesDevice -> BobsMessagingNode: Contact Bob


@enduml