@startuml
autonumber

participant "My City\nApp" as app

participant "Location\nHyperty" as myLocationHyperty

participant "Location\nData Object" as myLocationDO

participant "Generic Sensor\nAPI" as sensorAPI

participant "GPS\nAPI" as locationAPI

participant "Syncher" as sync

create myLocationHyperty

app ->  myLocationHyperty : new()

group discover available Context Location 

app ->  myLocationHyperty : discoverLocationContext()

myLocationHyperty -> sensorAPI : discoverSensors(  )

myLocationHyperty <-- sensorAPI : list of Sensors

alt Check GPS sensor

myLocationHyperty -> myLocationHyperty : check GPS Sensor Exists

else GPS Sensor Exists

create locationAPI

myLocationHyperty -> locationAPI : new

myLocationHyperty -> sync : create(  )

create myLocationDO 

sync -> myLocationDO : new

sync -> sync : Object.observe\n( myLocation, syncCallback )

myLocationHyperty <-- sync : return myHeart

end

app <--  myLocationHyperty : return myLocation Context

app -> app : Object.observe\n( myLocation, callback )

@enduml
