@startuml

left to right direction
skinparam packageStyle rect

actor Tourist
actor TourismAppDeveloper
actor CatalogServiceProvider
actor Hotel


rectangle TouristApplicationScenario {



TourismAppDeveloper -- (develop tourism application)
CatalogServiceProvider -- (offer tourism application)
(offer tourism application) .> (develop tourism application) : <<uses>>
(install tourism application) .> (offer tourism application) : <<uses>>


Tourist -- (install tourism application)
Tourist -- (collect context data)
Tourist -- (create profile)
Tourist -- (upload profile data)
(create profile) .> (upload profile data) : <<uses>>
(collect context data) .> (upload profile data) : <<uses>>


Tourist -- (publish profile)

Tourist -- (H2H call)
(display trust level) .> (H2H call) : <<extends>>

Hotel -- (show pulic profiles of ad-hoc community)
(show pulic profiles of ad-hoc community) .> (publish profile) : <<uses>>


Hotel -- (group message to ad-hoc community)

Tourist -- (add contact to graph connector)
Tourist -- (add information of contact's contacts into graph connector)
(add information of contact's contacts into graph connector) .> (add contact to graph connector) : extends

'note right of (forward message on graph edges)
'<<invariant>>
'{graph data is loaded}
'end note


}

@enduml